export * from './SilveiraIcon';
export { default as SilveiraIcon } from './SilveiraIcon';
export * from './ArrowIcon';
export { default as ArrowIcon } from './ArrowIcon';
export * from './LinkedInIcon';
export { default as LinkedInIcon } from './LinkedInIcon';
export * from './DesignerIcon';
export { default as DesignerIcon } from './DesignerIcon';
export * from './SchoolIcon';
export { default as SchoolIcon } from './SchoolIcon';
export * from './LaptopIcon';
export { default as LaptopIcon } from './LaptopIcon';
export * from './HistoryIcon';
export { default as HistoryIcon } from './HistoryIcon';
